export const AUDIT_CATEGORIES = {
  READ: 'read',
  UPLOAD: 'upload',
  DOWNLOAD: 'download',
  EDIT: 'edit',
  DELETE: 'delete',
  MOVE: 'move',
  PERMISSIONS: 'permissions',
  USERS: 'users',
  GROUPS: 'groups',
  FOLDERS: 'folders',
  AUTH: 'auth',
  SYSTEM: 'system',
  RECRUITING: 'recruiting',
};

export const AUDIT_ACTIONS = {
  FILE_UPLOAD: 'FILE_UPLOAD',
  FILE_DOWNLOAD: 'FILE_DOWNLOAD',
  FILE_READ: 'FILE_READ',
  FILE_EDIT: 'FILE_EDIT',
  FILE_DELETE: 'FILE_DELETE',
  FILE_MOVE: 'FILE_MOVE',
  FILE_RENAME: 'FILE_RENAME',

  MY_FILE_UPLOAD: 'MY_FILE_UPLOAD',
  MY_FILE_DOWNLOAD: 'MY_FILE_DOWNLOAD',
  MY_FILE_READ: 'MY_FILE_READ',
  MY_FILE_DELETE: 'MY_FILE_DELETE',

  FOLDER_CREATE: 'FOLDER_CREATE',
  FOLDER_RENAME: 'FOLDER_RENAME',
  FOLDER_MOVE: 'FOLDER_MOVE',
  FOLDER_DELETE: 'FOLDER_DELETE',
  FOLDER_DELETE_DENIED: 'FOLDER_DELETE_DENIED',

  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_UPDATE: 'GROUP_UPDATE',
  GROUP_DELETE: 'GROUP_DELETE',

  PERMISSION_ADD: 'PERMISSION_ADD',
  PERMISSION_REMOVE: 'PERMISSION_REMOVE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  ROLE_CHANGE: 'ROLE_CHANGE',

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSWORD_RESET: 'PASSWORD_RESET',

  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
  SYSTEM_CONFIGURATION_CHANGE: 'SYSTEM_CONFIGURATION_CHANGE',

  LEAD_CREATE: 'LEAD_CREATE',
  LEAD_IMPORT: 'LEAD_IMPORT',
  LEAD_UPDATE: 'LEAD_UPDATE',
  LEAD_REASSIGN: 'LEAD_REASSIGN',
  LEAD_ARCHIVE: 'LEAD_ARCHIVE',
  LEAD_COMMENT_ADD: 'LEAD_COMMENT_ADD',
  LEAD_COMMENT_EDIT: 'LEAD_COMMENT_EDIT',
  LEAD_SOURCE_CREATE: 'LEAD_SOURCE_CREATE',
};

export const TARGET_TYPES = {
  FILE: 'file',
  PERSONAL_FILE: 'personal_file',
  FOLDER: 'folder',
  USER: 'user',
  GROUP: 'group',
  PERMISSION: 'permission',
  ROLE: 'role',
  SYSTEM: 'system',
  AUTH: 'auth',
  LEAD: 'lead',
  LEAD_SOURCE: 'lead_source',
};
